# Generated by Django 4.2.7 on 2023-12-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
